version: '3'
services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  web:
    build: .
    command: /bin/sh -c "rm -rf tmp/pids/server.pid && ./bin/dev"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - db
    tty: true
    stdin_open: true
  redis:
    image: redis:latest
    ports:
      - "6380:6380"

volumes:
  postgres_volume:
